### ISSUE TITLE
CDR file conversion is failure

### ISSUE THREAD

**Issue by sxgkwei** [sk1project/uniconvertor#18]
[3.zip](https://github.com/sk1project/uniconvertor/files/3885821/3.zip)
2 test file in the zip.
They are normally converted on  https://cloudconvert.com/cdr-to-png .  but uniconvertor is error.
Or uniconvertor uses strict mode, which causes a slight deviation of the file, which will lead to failure. Can you use loose mode?

win7  uniconvertor-2.0rc4-win64_headless.msi

**Comment by sk1project** [comment]
Hi! Thank you for reported issue. Actually it's just a result of incomplete implementation. Current rc5 milestone should resolve this issue:

https://sk1project.net/news/2019-05-27/sk1-and-uniconvertor-2.0rc4-binaries/

Btw we have tested cloudconvert.com and found that it fails on some CDR file formats. They also have not a perfect translator.

**Comment by sxgkwei** [comment]
> Hi! Thank you for reported issue. Actually it's just a result of incomplete implementation. Current rc5 milestone should resolve this issue:
> 
> https://sk1project.net/news/2019-05-27/sk1-and-uniconvertor-2.0rc4-binaries/
> 
> Btw we have tested cloudconvert.com and found that it fails on some CDR file formats. They also have not a perfect translator.

hi，I can't understand how complete it is. I try to install sk1-2.0rc4-win64_headless.msi，but the problem remains. And I guess, you don't mean that I want to install both sK1 and UniConvertor?

UniConvertor rc5 didn't solve my problem either . But when I try to install the older version UniConvertor-1.1.6pre_rev.1313-290.msi . The test file 3.cdr I provided can be converted successfully.

This is really a weird problem. Perhaps the test files I can find contain some defects in themselves. However, the update of the UniConvertor version seems to have weakened the ability to handle defective files.

**Comment by sk1project** [comment]
sK1 and UniConvertor are standalone applications and don't interfere between themselves. Actually UniConvertor is a core part of sK1. So sK1 has own copy of UniConvertor. Therefore applications are developed synchronously. sK1 and UniConvertor 2.0 are written from scratch and not all features from UniConvertor 1.x have been transferred. It's just the matter of time. Be patient and stay with us! All features of CDR format importing will be in latest version.
